# Generated by Django 5.0 on 2023-12-29 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpiprj', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'managed': True},
        ),
    ]
