# Generated by Django 5.0 on 2024-04-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpiprj', '0002_alter_project_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase_ref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_ref_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'phase_ref',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': False},
        ),
    ]
